[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
hannoy = { path = "../"}
heed = "0.22.0"
ordered-float = "5.0.0"
roaring = "0.11.2"
tempfile = "3.20.0"
rand = { version = "0.8.5", features = ["alloc"] }
